version: "3"
services:
  web:
    image: test
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - ./:/src
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
