version: "3"
services:
  web:
    image: apinode
    env_file:
     - .env
    environment:
     - DB_HOST=mongo
     - DB_PORT=27017
     - DB_NAME=newscoin
     - SERVER_PORT=3000

    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
